find . -type f -name "*.scala" | xargs perl -pi -e 's/package scalaz/package org.specs2.internal.scalaz/g' 
find . -type f -name "*.scala" | xargs perl -pi -e 's/package object scalaz/package org.specs2.internal; package object scalaz/g' 
find . -type f -name "*.scala" | xargs perl -pi -e 's/extends scalaz/extends org.specs2.internal.scalaz/g'
find . -type f -name "*.scala" | xargs perl -pi -e 's/with scalaz/with org.specs2.internal.scalaz/g' 
find . -type f -name "*.scala" | xargs perl -pi -e 's/new scalaz/new org.specs2.internal.scalaz/g' 
find . -type f -name "*.scala" | xargs perl -pi -e 's/import scalaz/import org.specs2.internal.scalaz/g' 
find . -type f -name "*.scala" | xargs perl -pi -e 's/: scalaz./: org.specs2.internal.scalaz./g' 
find . -type f -name "*.scala" | xargs perl -pi -e 's/= scalaz./= org.specs2.internal.scalaz./g' 
find . -type f -name "*.scala" | xargs perl -pi -e 's/, scalaz./, org.specs2.internal.scalaz./g' 
find . -type f -name "build.scala" | xargs perl -pi -e 's/organization := "scalaz"/organization := "org.specs2"/g' 
